"""baseline schema

Full schema as of the first alembic-managed deployment. Captures
every table, column, index, and unique constraint that existed
under the old `create_all() + _ensure_columns()` regime, plus the
`webhook_events` table introduced earlier in this branch.

For existing production databases (which already have this schema
in place from `create_all`), `init_db` stamps this revision
instead of running the upgrade, so we never try to re-create an
existing table.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-24
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_connect_account_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payouts_enabled', sa.Boolean(), nullable=True),
    sa.Column('etsy_access_token', sa.Text(), nullable=True),
    sa.Column('etsy_refresh_token', sa.Text(), nullable=True),
    sa.Column('etsy_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etsy_shop_id', sa.String(length=255), nullable=True),
    sa.Column('etsy_shop_name', sa.String(length=255), nullable=True),
    sa.Column('etsy_pkce_verifier', sa.Text(), nullable=True),
    sa.Column('generation_count_this_month', sa.Integer(), nullable=True),
    sa.Column('month_reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'event_id', name='uq_webhook_source_event')
    )
    op.create_table('generated_files',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('osm_id', sa.Integer(), nullable=False),
    sa.Column('osm_type', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('display_text', sa.String(length=255), nullable=False),
    sa.Column('board_size', sa.String(length=20), nullable=False),
    sa.Column('board_width_mm', sa.Float(), nullable=False),
    sa.Column('board_height_mm', sa.Float(), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=False),
    sa.Column('show_coordinates', sa.Boolean(), nullable=True),
    sa.Column('font_size_mm', sa.Float(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=True),
    sa.Column('path_count', sa.Integer(), nullable=True),
    sa.Column('layer_count', sa.Integer(), nullable=True),
    sa.Column('svg_storage_key', sa.String(length=512), nullable=False),
    sa.Column('dxf_storage_key', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('print_png_key', sa.String(length=512), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_files_osm_id'), 'generated_files', ['osm_id'], unique=False)
    op.create_index(op.f('ix_generated_files_owner_id'), 'generated_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_generated_files_product_type'), 'generated_files', ['product_type'], unique=False)
    op.create_index(op.f('ix_generated_files_province'), 'generated_files', ['province'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('design_credits',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('etsy_receipt_id', sa.String(length=100), nullable=True),
    sa.Column('etsy_shop_id', sa.String(length=100), nullable=True),
    sa.Column('etsy_buyer_email', sa.String(length=255), nullable=True),
    sa.Column('seller_id', sa.String(length=36), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('product_tier', sa.String(length=20), nullable=True),
    sa.Column('etsy_listing_title', sa.String(length=500), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('redeem_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('design_config', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('file_id', sa.String(length=16), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['generated_files.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_credits_etsy_receipt_id'), 'design_credits', ['etsy_receipt_id'], unique=False)
    op.create_index(op.f('ix_design_credits_redeem_token'), 'design_credits', ['redeem_token'], unique=True)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('file_id', sa.String(length=16), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('sale_count', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['generated_files.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_marketplace_listings_seller_id'), 'marketplace_listings', ['seller_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('listing_id', sa.String(length=16), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('platform_fee_cents', sa.Integer(), nullable=False),
    sa.Column('seller_payout_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'buyer_id', name='uq_purchase_listing_buyer')
    )
    op.create_index(op.f('ix_purchases_buyer_id'), 'purchases', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_purchases_listing_id'), 'purchases', ['listing_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('listing_id', sa.String(length=16), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('cnc_compatible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'buyer_id', name='uq_review_listing_buyer')
    )
    op.create_index(op.f('ix_reviews_listing_id'), 'reviews', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_listing_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_purchases_listing_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_buyer_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_marketplace_listings_seller_id'), table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_design_credits_redeem_token'), table_name='design_credits')
    op.drop_index(op.f('ix_design_credits_etsy_receipt_id'), table_name='design_credits')
    op.drop_table('design_credits')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_generated_files_province'), table_name='generated_files')
    op.drop_index(op.f('ix_generated_files_product_type'), table_name='generated_files')
    op.drop_index(op.f('ix_generated_files_owner_id'), table_name='generated_files')
    op.drop_index(op.f('ix_generated_files_osm_id'), table_name='generated_files')
    op.drop_table('generated_files')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
